displayName=Wiki Tag Bank Highlighter
author=Chris Brown kulcris1
description=Highlights items in your bank or creates a banktab based on a wiki category
tags=Wiki, Bank
plugins=com.wikitagbankhighlighter.WikiBankToolsPlugin